# Generated by Django 4.0.6 on 2022-07-28 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttranslation',
            name='description',
            field=models.TextField(),
        ),
    ]
