version: "3.8"
services:
  web:
    build: ./app
    #command: sh -c "python manage.py collectstatic --no-input && python manage.py makemigrations && python manage.py migrate"
    command: python manage.py runserver 0.0.0.0:8083
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8083:8083
    
    env_file:
      - ./app/.env
    
    environment:
      - DB_NAME=portfolio_db
      - DB_USER=postgres
      - DB_PASSWORD=admin12345
      - DB_HOST=pg
      - DB_PORT=5432
      - DATABASE=postgres
      
    depends_on:
      - pg

  pg:
      container_name: pg_container_nucamp
      image: postgres:13.2-alpine
      restart: always
      environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: admin123
          POSTGRES_DB: nucamp_final_db
          POSTGRES_HOST_AUTH_METHOD: trust
      volumes:
          - ./data:/data
          - ./data/misc/django_init.sql:/docker-entrypoint-initdb.d/1-django-init.sql
  pgadmin:
      container_name: pgadmin_container_nucamp
      image: dpage/pgadmin4:6.11
      restart: always
      environment:
          PGADMIN_DEFAULT_EMAIL: admin@example.com
          PGADMIN_DEFAULT_PASSWORD: admin123
          PGADMIN_LISTEN_PORT: 5433
          PGADMIN_CONFIG_SERVER_MODE: "False"
          PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
      ports:
          - "5433:5433"
      depends_on:
          - pg

