version: "3.8"
services:
  web:
    build: ./app
    #command: sh -c "python manage.py collectstatic --no-input && python manage.py makemigrations && python manage.py migrate"
    command: python manage.py runserver 0.0.0.0:8083
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8083:8083
    
    env_file:
      - ./app/.env
    
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DATABASE=${DATABASE}
      
    depends_on:
      - pg

  pg:
      container_name: pg_container_nucamp
      image: postgres:13.2-alpine
      restart: always
      environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: admin123
          POSTGRES_DB: nucamp_final_db
          POSTGRES_HOST_AUTH_METHOD: trust
      volumes:
          - ./data:/data
          - ./data/misc/django_init.sql:/docker-entrypoint-initdb.d/1-django-init.sql
  pgadmin:
      container_name: pgadmin_container_nucamp
      image: dpage/pgadmin4:6.11
      restart: always
      environment:
          PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
          PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
          PGADMIN_LISTEN_PORT: ${PGADMIN_LISTEN_PORT}
          PGADMIN_CONFIG_SERVER_MODE: ${PGADMIN_CONFIG_SERVER_MODE}
          PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: ${PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED}
      ports:
          - "5433:5433"
      depends_on:
          - pg

