# Generated by Django 4.0.6 on 2022-07-21 20:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonials',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='testimonials',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testimonials',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
