# Generated by Django 4.0.6 on 2022-08-05 16:35

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_posttranslation_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posttranslation',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
    ]
