# Generated by Django 4.0.6 on 2022-08-06 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_posttranslation_body'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_on', 'id']},
        ),
    ]
