# Generated by Django 4.0.6 on 2022-07-29 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_obtained_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
