# Generated by Django 4.0.6 on 2022-07-29 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='categories',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
