# Generated by Django 4.0.6 on 2022-07-29 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='plataform',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
