# Generated by Django 4.0.6 on 2022-08-10 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_rename_plataform_course_platform'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['created_on']},
        ),
    ]
