# Generated by Django 4.0.6 on 2022-08-10 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_hometranslation_description_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='class_css',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
