# Generated by Django 4.0.6 on 2022-08-10 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_home_class_css'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hometranslation',
            name='title',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
