# Generated by Django 4.0.6 on 2022-08-06 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_alter_resumetranslation_board1'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumetranslation',
            name='jobs',
            field=models.JSONField(null=True),
        ),
    ]
