# Generated by Django 4.0.6 on 2022-08-06 20:12

from django.db import migrations
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_resumetranslation_jobs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resumetranslation',
            name='job1',
        ),
        migrations.AddField(
            model_name='resumetranslation',
            name='job_test',
            field=picklefield.fields.PickledObjectField(editable=False, null=True),
        ),
    ]
