# Generated by Django 4.0.6 on 2022-08-06 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_remove_resumetranslation_job1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='description',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='education',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='interests',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='languagues',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='resumetranslation',
            name='board1',
        ),
        migrations.RemoveField(
            model_name='resumetranslation',
            name='job_company',
        ),
        migrations.RemoveField(
            model_name='resumetranslation',
            name='job_test',
        ),
        migrations.RemoveField(
            model_name='resumetranslation',
            name='job_time',
        ),
        migrations.AddField(
            model_name='resumetranslation',
            name='awards',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='resumetranslation',
            name='education',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='resumetranslation',
            name='interests',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='resumetranslation',
            name='languagues',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='resumetranslation',
            name='skills',
            field=models.JSONField(null=True),
        ),
    ]
