# Generated by Django 4.0.6 on 2022-08-10 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0006_remove_resume_description_remove_resume_education_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='asidetranslation',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='asidetranslation',
            name='master',
        ),
        migrations.DeleteModel(
            name='Aside',
        ),
        migrations.DeleteModel(
            name='AsideTranslation',
        ),
    ]
